import "./globals.css";
import Header from "@/components/shared/header";
import Footer from "@/components/shared/footer";
import { AuthProvider } from "@/utils/useAuth";

export const metadata = {
  title: "Pray For",
  description: "Generated by YS",
};

export default function RootLayout({ children }) {
  return (
    <AuthProvider>
      <html lang="en">
        <body id="container">
          <Header />
          <main id="main">{children}</main>
          <Footer />
        </body>
      </html>
    </AuthProvider>
  );
}
