import "@/styles/globals.css";
import Header from "@/components/shared/header";
import Footer from "@/components/shared/footer";

export const metadata = {
  title: "Pray For",
  description: "Generated by YS",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
